export declare const APP_BAR_HEIGHT = 56;
export type AppBarProps = React.ComponentProps<'header'>;
export declare const AppBar: ({ style, className, ...props }: AppBarProps) => import("react/jsx-runtime").JSX.Element;
export type AppBarTitleProps = React.ComponentProps<'h3'>;
export declare const AppBarTitle: ({ className, ...props }: AppBarTitleProps) => import("react/jsx-runtime").JSX.Element;
export type AppBarActionProps = React.ComponentProps<'div'>;
export declare const AppBarAction: ({ ...props }: AppBarActionProps) => import("react/jsx-runtime").JSX.Element;
export type AppBarExtraProps = React.ComponentProps<'div'>;
export declare const AppBarExtra: ({ className, ...props }: AppBarExtraProps) => import("react/jsx-runtime").JSX.Element;
